# @format

name: miscelaneos
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.10
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  permission_handler: ^11.2.0
  riverpod_annotation: ^2.3.4
  sensors_plus: ^4.0.2
  share_plus: ^7.2.2

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
